### ISSUE TITLE
Add `parallel` installer action

### ISSUE THREAD

**Issue by allanlei** [swaglive/actions#3]
Only the `macos` runner has it.  Would be great to have it on `ubuntu`

* Add GNU `parallel` compiled per runner
* Setup via `::add-path::{path}`

**Comment by RammusXu** [comment]
I created a pr for adding `parallel` in ubuntu: https://github.com/actions/virtual-environments/pull/205

In the same time, I thought we can use this step rather than creating an action.
```
    - name: Set env
      run: |
        sudo apt-get install parallel
```
